
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE2_115(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// Sma //////////
	input 		          		SMA_CLKIN,
	output		          		SMA_CLKOUT,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,




	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [6:4]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
	wire OE_to_tri;


    top top (.OE_to_tri(OE_to_tri), .out_tri(GPIO[6]));

    top_level top_level (.local_clk(CLOCK_50), .first_segment(HEX0), .second_segment(HEX1), .third_segment(HEX2), .fourth_segment(HEX3), .local_signal(GPIO[6]), .local_presense(LEDG[0]), .OE_to_tri(OE_to_tri), .SW(SW[2:0]));



//=======================================================
//  Structural coding
//=======================================================

	assign LEDR = SW;
    assign HEX4 = 0;
    assign HEX5 = 0;
    assign HEX6 = 0;
    assign HEX7 = 0;
    
    assign GPIO[5] = 1'b1;
    assign GPIO[4] = 1'b0;

    assign LEDG[7:1] = 0;

endmodule
